Меняй-удаляй
htmlacademy-ecmascript/678357-cinemaddict-17 pull request #13
Opened 2022-06-04 06:48 UTC by Gravi7ON

Сенсей привет :wave:. Реализовал часть функционала, проверь пожалуйста на корректность, в том ли направлении работаю, сложности возникли с попапом, пока не сообразил как сделать чтобы не перерисовывался вместе со всем, может все-таки презентер для него нужен? Остальное вроде все оке, фильтрация есть, заглушки тоже вроде работают. Да, и не могу понять сортировка по умолчанию нарушается только при фильтре all, при остальных фильтрах работает все корректно если не трогать после загрузки приложения сортировку по умолчанию

2022-06-04 17:53 UTC, andreevsm requested changes

2022-06-04 17:53 UTC, andreevsm commented on src/model/films-model.js
> +  deleteFilmComment = (updateType, films) => {
1. Хмм так а где реализация метода? То есть все что он делает, уведомляет подписчиков?)
2. Можно назвать просто `deleteComment`

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/film-presenter.js
> +    const index = this.#film.comments.findIndex((comment) => comment.id === evt.target.id);
Вот как раз всю эту часть нужно перенести в `deleteFilmComment`
Чтобы мы просто передавали `evt.target.id`, а уже в том методе удаляли по id коммент)

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/film-presenter.js
> +      UserAction.DELETE_FILM,
Давай переименуем в DELETE_COMMENT, раз мы тут коммент удаляем, а не фильм)

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/films-presenter.js
> +      this.#renderSortMenu(RenderPosition.BEFOREBEGIN);
Метод используется один раз, поэтому можно внутри него и указать `RenderPosition`, зачем отдельно прокидывать значение?)

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/films-presenter.js
> +    } else {
Давай лучше так сделаем:
```
this.#renderedFilmCount = resetRenderedFilmsCount ? FILMS_COUNT_PER_STEP : Math.min(filmCount, this.#renderedFilmCount);
```

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/films-presenter.js
> +        this.#filmsModel.deleteFilmComment(updateType, update);
Хмм а у нас update - это не объект случайно? Просто `deleteFilmComment` вторым аргументом принимает `films`

2022-06-04 17:53 UTC, andreevsm commented on src/presenter/filter-presenter.js
> +    const filters = this.filters;
А вот это лишнее, давай просто свойство везде использовать)

2022-06-05 05:23 UTC, Gravi7ON commented on src/presenter/films-presenter.js
> +        this.#filmsModel.deleteFilmComment(updateType, update);
Да это объект конкретного фильма у которого нужно удалить конкретный комментарий, его особо не переименуешь, потому что в `this.#filmsModel.updateFilm(updateType, update)` нужно обновлять, а там удалять, можно назвать toUpdate если необходимо

2022-06-06 09:54 UTC, andreevsm requested changes

2022-06-06 09:54 UTC, andreevsm commented on src/model/films-model.js
> +  deleteComment = (updateType, update, evt) => {
А зачем тянуть весь объект `evt`, если мы только id используем?)
Давай лучше будем сразу `id` принимать

Ну и вызывать:
`deleteComment(updateType, update, evt.target.id)`

2022-06-06 09:54 UTC, andreevsm commented on src/model/films-model.js
> +    const refreshComments = film.comments;
Лишняя переменная, можно сразу `film.comments.splice(...`

2022-06-06 09:54 UTC, andreevsm commented on src/model/films-model.js
> +    const commentElement = document.querySelector('.film-details__comment-input').value;
Блин, может я не так выразился, как раз 40 и 41 строки нужно перенести в film-presenter или даже в popup-view, чтобы в `films-model` уже попадал объект с emotion и comment

2022-06-06 09:54 UTC, andreevsm commented on src/model/films-model.js
> +    refreshComments.splice(indexDeletingComment, DELETE_COUNT);
Давай все-таки сделаем по красоте через иммутабельность, то есть при изменении комментов фильма нужно обновлять весь фильм))
Потому что изменение объекта по ссылке может выстрелить в ногу в будущем

Должно что-то такое получиться
```
this.#films = [
  ...this.#films.slice(...),
  {
    ...update,
    comments: [тут новый список комментов]
  },
  ...this.#films.slice(...)
]
```

2022-06-06 09:54 UTC, andreevsm commented on src/model/films-model.js
> +    refreshComments.push(newCommnet);
И тут давай тоже обновлять фильм)

2022-06-07 16:38 UTC, andreevsm requested changes

2022-06-07 16:38 UTC, andreevsm commented on src/presenter/film-presenter.js
> +      const newPopup = document.querySelector('.film-details');
Хмм а как это работает? У нас две переменные с одинаковым попапом)
Давай все-таки одной воспользуемся

2022-06-07 16:38 UTC, andreevsm commented on src/presenter/film-presenter.js
> +      'date': '2019-05-11T16:12:32.554Z',
Что-то вылетело из головы, дату же тоже надо новую указывать

2022-06-07 17:08 UTC, merged