Дополнительная функциональность
htmlacademy-ecmascript/678357-cinemaddict-17 pull request #16
Opened 2022-06-15 14:48 UTC by Gravi7ON

Сенсей привет!) частично реализовал, немного заблудился), посмотри в верном ли направлении двигаюсь? Сейчас отрисовка и динамическое изменение доп блоков работают, а именно: отсутсвие по нулям, изменение количества комментов, все что связано с отрисовкой, работают кнопки добавления/удаления по категориям, не работает попап у доп блоков, не пойму как добраться до него как добираюсь до карточек в этих блоках. Глянь, посоветуй как лучше сделать или вообще все переделать?) Код конечно мудреный получился)))

---
:mortar_board: [Дополнительная функциональность](https://up.htmlacademy.ru/ecmascript/17/user/678357/tasks/17)

---
:mortar_board: [Дополнительная функциональность](https://up.htmlacademy.ru/ecmascript/17/user/678357/tasks/17)

2022-06-15 19:29 UTC, andreevsm requested changes

2022-06-15 19:29 UTC, andreevsm commented on src/presenter/film-presenter.js
> +      evt
Не совсем целесообразно прокидывать целый объект `evt` ради определения, к какому блоку он относится)

2022-06-15 19:29 UTC, andreevsm commented on src/presenter/films-presenter.js
> +        randomRated.push(films[getRandomUniquePositiveInteger(0, films.length - 1)()]);
Какой-то сложноватый алгоритм получился)
Нам же просто нужно:
1. Отсортировать по рейтингу
2. Взять первые два элемента отсортированного массива

2022-06-15 19:29 UTC, andreevsm commented on src/presenter/films-presenter.js
> +    for (const filmCard of films.sort(sortFilmsRating).slice(0, 2)) {
У нас на каждую итерацию будет запускаться сортировка, тоже не очень оптимизированно(
Давай вынесем это за пределы цикла тогда уже

2022-06-15 19:29 UTC, andreevsm commented on src/presenter/films-presenter.js
> +      const currentPopupCommentedComponent = this.#filmCommentedPresenter.get(update.id)._popupComponent;
`this.#filmCommentedPresenter.get(update.id)` - эту часть давай вынесем в отдельную переменную в начале условия, чтоб два раза не обращаться к одному и тому же свойству)

2022-06-15 19:29 UTC, andreevsm commented on src/presenter/films-presenter.js
> +        // this.#filmRatedPresenter.get(update.id).rerenderPopup(comments, this.#currentPopupPosition);
Удаляем?

2022-06-16 14:03 UTC, Gravi7ON commented on src/presenter/films-presenter.js
> +      const currentPopupCommentedComponent = this.#filmCommentedPresenter.get(update.id)._popupComponent;
Здесь есть проблемы, я это пробовал и в последнем коммите тоже, поэтому вернул в исходное

2022-06-16 14:32 UTC, Gravi7ON commented on src/presenter/films-presenter.js
> +          this.#filmRatedPresenter.get(update.id).rerenderPopup(comments, this.#currentPopupPosition);
Здесь и ниже в подобных строках нужен новый презентер после очистки, поэтому думаю нет смысла в переменной

2022-06-16 14:36 UTC, Gravi7ON commented on src/presenter/films-presenter.js
> +
Всё ниже нужно в `if` возводить и проверку писать на равенство `undefined` чтобы избавиться от вызовов презентеров, вроде как некрасиво будет, поэтому оставил так, на твое усмотрение!?

2022-06-16 22:49 UTC, merged